### ISSUE TITLE
添加不了服务，添加就出错

### ISSUE THREAD

**Issue by duffercn** [lrhh123/ChatGPT-On-CS#2]
<img width="512" alt="image" src="https://github.com/lrhh123/ChatGPT-On-CS/assets/716704/4000d49b-933a-4093-9559-6219bc54bf24">

**Comment by alsritter** [comment]
稍等，这个问题已经确认了，这几天会修复

**Comment by lrhh123** [comment]
已修复 v1.0.3 版本
