### ISSUE TITLE
能否只使用自动关键字回复功能？

### ISSUE THREAD

**Issue by mooutiandian** [lrhh123/ChatGPT-On-CS#7]
用于抖店
想问，该软件能否只使用“自动关键字回复”的功能
暂时没有GPT的需求，如果可以应该怎么设置呢？

现在使用抖店不会自动回复是必须添加GPT才可以使用吗？
但是加了GPT后，我不想用AI的“未匹配调用GPT”的功能
有什么办法设置吗？

**Comment by lrhh123** [comment]
加到 TODO 了，你可以进群，有更新第一时间通知你

**Comment by lrhh123** [comment]
已支持
